### ISSUE TITLE
Downloading some pururin mangas cause an unhandled error.

### ISSUE THREAD

**Issue by wightwulf1944** [csaki/Hentoid#15]
When pururin returns an error 521 when hentoid is trying to collect links for download, an "unhandled error" notification is returned to the user.

When this error happens, an empty folder with the manga name is created in the downloads directory.

Affects version: 1.0.8

Frequency: 1/5. Issue happens depending on pururin server.

Repro steps:
1. Download several mangas from pururin.
2. Observe the device notifications.

Result: The download fails and an "unhandled error" notification is shown.

**Comment by csaki** [comment]
Yes, this error happens when Pururin return a not valid html (server busy and things like that).
What do you suggest in that cases?

**Comment by neosubmarino** [comment]
These are the main issues:
1. The error message is ambiguous so the user does not know what the problem is - the app or the server?
2. There is an empty folder made when this happens which is undesirable.
3. The app has the "try again" feature but is not offered in this case.

Returning a specific error message would be too much work considering the possible pururin errors.

How bout a general "server error" message and then offering to try again similar to download errors. And a folder should only be made if the links are parsed successfully and an image is ready to be downloaded.

The above suggestions should fix the main issues but please do not consider them to be the best solutions. If there's any way you can fix the above issues with less work then that's great. Good luck!

**Comment by csaki** [comment]
1 .- Message: "Server error.\nThe download was paused. You can resume it in Download Manager."
2 .- Well, if the folder is empty, I'm going to delete it.
3 .- The download is just paused, you can resume it.

**Comment by neosubmarino** [comment]
Sounds good. Try not to overwork yourself ok?

**Comment by neosubmarino** [comment]
We're getting reports that this issue has been happening more often recently and unfortunately due to the ambiguity of the error message we're not able to get additional information. I don't have equipment for packet sniffing to test this.

A good way to get more info about this is to echo the unexpected url to the debug stream.
http://stackoverflow.com/questions/6601165/android-ddms-logging-reached-urls

It is also for the best to make the notification more concise so the users know it's a problem with the server and not the app.

**Comment by wightwulf1944** [comment]
Now that pururin is no longer available this issue is no longer relevant.
